version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  gh-pages: sugarshin/gh-pages@0.0.6
workflows:
  version: 2
  build:
    jobs:
      - test
          # filters:
          #   branches:

jobs:
  test:
    resource_class: xlarge
    machine:
      image: ubuntu-2004:202008-01

    steps:
      - checkout
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt update
          #sudo apt install -y openjdk-8-jdk
      - run: |
          scripts/load-neo.sh
          scripts/load-mem.sh
          scripts/load-red.sh
