# CI configuration that runs the benchmark on the small data set included in the repository
version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    # resource_class: xlarge
    machine:
      image: ubuntu-2004:202008-01

    steps:
      - checkout
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt update
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --upgrade pip
            scripts/install-dependencies.sh
      - run:
          name: Preprocess data
          command: |
            scripts/preprocess.sh
            scripts/convert-to-ntriples.sh
      - run:
          name: Test Neo4j
          command: |
            cd neo
            ./pre-load.sh; ./load.sh; ./post-load.sh; ./run.sh; ./stop.sh
            cd ..
      - run:
          name: Test Memgraph
          command: |
            cd mem
            ./pre-load.sh; ./load.sh; ./post-load.sh; ./run.sh; ./stop.sh
            cd ..
      - run:
          name: Test DuckDB
          command: |
            cd ddb
            ./pre-load.sh; ./load.sh; ./post-load.sh; ./run.sh; ./stop.sh
            cd ..
      - run:
          name: Test PostgreSQL
          command: |
            cd pos
            ./pre-load.sh; ./load.sh; ./post-load.sh; ./run.sh; ./stop.sh
            cd ..
      - run:
          name: Test RedisGraph
          command: |
            export PATH="~/.local/bin:$PATH"
            cd red
            ./pre-load.sh; ./load.sh; ./post-load.sh; ./run.sh; ./stop.sh
            cd ..
      - run:
          name: Test Virtuoso
          command: |
            cd vos
            ./pre-load.sh; ./load.sh; ./post-load.sh; ./run.sh; ./stop.sh
            cd ..
      - run:
          name: Test RapidMatch
          command: |
            rdm/get.sh
            ddb/load.sh; rdm/convert.sh
            cd rdm
            cd ..
      - slack/status
