version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  gh-pages: sugarshin/gh-pages@0.0.6
workflows:
  version: 2
  build:
    jobs:
      - test
# filters:
#   branches:

jobs:
  test:
    resource_class: xlarge
    machine:
      image: ubuntu-2004:202008-01

    steps:
      - checkout
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt update
          #sudo apt install -y openjdk-8-jdk
      - run:
          name: Install dependencies
          command: |
            scripts/install-clients.sh
      - run:
          name: Preprocess data
          command: |
            scripts/preprocess.sh
      - run:
          name: Load data
          command: |
            scripts/load-neo.sh
            scripts/load-red.sh
      - run:
          name: Run queries
          command: |
            python3 clients/neo.py
            python3 clients/red.py
